seed: 0
output_dir: ./st_mem/mask_B64_RE
exp_name: pretrain
resume: null
# resume_pretrain: /tf/yg/ST-MEM/st_mem/mask_B64/pretrain/checkpoint-44.pth
start_epoch: 0
model_name: st_mem_vit_base_dec256d4b
device: cuda:0

ddp:
  world_size: 1
  rank: -1
  gpu: 0
  dist_url: env://
  dist_backend: nccl
  distributed: false

model:
  seq_len: 2250
  patch_size: 75
  num_leads: 12
  norm_pix_loss: true

dataset:
  filename_col: RELATIVE_FILE_PATH
  fs_col: SAMPLE_RATE
  lead: 12lead
  fs: 250
  index_dir: /tf/yg/ST-MEM/data/
  ecg_dir: /tf/yg/ST-MEM/data/

  train_csv: chapman_ningbo_index.csv

  train_transforms:
  - random_crop:
      crop_length: 2250
  - highpass_filter:
      fs: 250
      cutoff: 0.67
  - lowpass_filter:
      fs: 250
      cutoff: 40
  - standardize:
      axis: [-1, -2]

dataloader:
  batch_size: 64
  num_workers: 0
  pin_memory: True

train:
  epochs: 100
  accum_iter: 2
  warmup_epochs: 10
  min_lr: 0
  blr: 0.00015
  lr: null
  weight_decay: 0.01
  optimizer: adamw
  optimizer_kwargs:
    betas: [0.9, 0.95]
